### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by cnmicha** [tacruc/gpgmailer#12]
Hi, what about adding localization to this app?

I would recommend using https://github.com/nextcloud/nextcloud-l10n and would offer to create a PR for that.

**Comment by tacruc** [comment]
Feel free, thanks.

**Comment by cnmicha** [comment]
@tacruc Do you have a preference for using transifex or do we like to edit the strings directly in the files?

**Comment by tacruc** [comment]
I think using transfex would be a good idea, as I only speak two languages.

**Comment by cnmicha** [comment]
I agree. Could you then please create a transifex project (because you are the repository owner)?
