### ISSUE TITLE
Compatibility with Nextcloud 24

### ISSUE THREAD

**Issue by l00v3** [tacruc/gpgmailer#24]
Hi,
nextcloud was [released](https://nextcloud.com/blog/nextcloud-hub-24-is-here/) recently. Please make the app compatible.
Thank you!

**Comment by tacruc** [comment]
Hi,
I'm just testing on my private instance currently. The app seems to work. Just update it.
I won't be able to publish a new release, before june.

**Comment by Tealk** [comment]
now you can probably update it directly for v25

**Comment by tacruc** [comment]
Just tested on my v25 installation. Seams to work

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo
