### ISSUE TITLE
key is not for your email

### ISSUE THREAD

**Issue by Luticus** [tacruc/gpgmailer#3]
I think something broke since I last tested.  I just installed the new Nextcloud 19 release and set up your 0.0.1 build and everything looks ok, but when I try to use my key which I exported from kelopatra, it says "Key is not for email" even though that's the only thing I've used it for.  Also I launched my nc 19 beta 2 virtual machine with the compiled code I tested and copied the key I uploaded to that server (it was the same key) and pasted it into my new 19.0.0 server only to get the same response. So in short, I can't upload my public key.

**Comment by tacruc** [comment]
Well the email used in the key has to be the same email which is used in for your nextcloud account.

You can find the one information in Settings->personal->Personal Information. This email has to be in the list you find in kleopatra when you do a right click and then details on the key.
I'm not shure if it is case sensitive or sensitive to possible white spaces.

**Comment by Luticus** [comment]
ah ok, lemmie check that.  it should be the same.

**Comment by Luticus** [comment]
OK, yea I think you do have a bug with case sensitivity. I changed my email from something like Luticus@Example.com to luticus@example.com and it worked. Probably shouldn't be quite that strict with the checking.

**Comment by tacruc** [comment]
There might be some space for improvement, but I have to make shure that gnupg find the key you are uploading with the email written in your profile. So I can only relax as much as gnupg is fuzzy in its search.
And I have to test this carefully before making a hot fix, which makes everything worse in the end.

**Comment by Luticus** [comment]
Yea, I understand. At least now I know what the source of the issue is and I can advise people of the workaround. My concern is simply confusion for the users, it's not like it's unworkable at this point. Honestly I'm just glad to finally have this feature working at all. Thanks for your help.

**Comment by Luticus** [comment]
#4 Added this pull request if you're interested, to address this issue.

**Comment by tacruc** [comment]
Cool thanks for your input, lets discuss it in the PR.

**Comment by tacruc** [comment]
Solved with #4
