### ISSUE TITLE
App "Gpg Mailer" cannot be installed because the following dependencies are not fulfilled

### ISSUE THREAD

**Issue by serversghost** [tacruc/gpgmailer#6]
Hi, can you please tell me which libraries I am missing, or that are required to install Gpg Mailer.
I get the following error when I try to download & enable Gpg Mailer from the Nextcloud app page:

> **App "Gpg Mailer" cannot be installed because the following dependencies are not fulfilled: The library gnupg is not available.** 

My server is running:
```
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
```
I've had a look around [gnupg.org](url) but I am unsure which specific library I require.
Any help would be great, thank you.

**Comment by tacruc** [comment]
I think php-gnupg so the php wrapper lib for php.
