### ISSUE TITLE
Nextcloud says that gnupg library is not accessible, but it is installed

### ISSUE THREAD

**Issue by GrifKies** [tacruc/gpgmailer#7]
App "Gpg Mailer" cannot be installed because the following dependencies are not fulfilled: The library gnupg is not available.
 I am unable to install gpgmailer because it does not recognise that I have gpg2/gnupg2 installed. I also have gpg/gnupg installed as well. Thank you for making this, and anything helps.

**Comment by tacruc** [comment]
Duplicate #6 you need the PHP library probably called php-gnupg
