### ISSUE TITLE
It seems this is for server signing cf client signing of mail

### ISSUE THREAD

**Issue by xpseudonym** [tacruc/gpgmailer#8]
Is that correct?

**Comment by tacruc** [comment]
CF?

**Comment by xpseudonym** [comment]
cf. = compare
Thx

**Comment by tacruc** [comment]
I still don't understand your question. It's singing and encrypting all system email from nextcloud to you or other users of your nextcloud server. Therefore I find it confusing to talk about server or clients. As the nextcloud server is acting as a smpt client. 

Addition: It has nothing to do with nextcloud mail app.

**Comment by xpseudonym** [comment]
Are the keys used system wide and not personal to the user? Who provides and keeps the private key(s)?

**Comment by tacruc** [comment]
The users just provided public keys, each user has the possibility to upload his key. There is one private key for the server which is used for signing.

**Comment by xpseudonym** [comment]
Thanks
Morgan
