### ISSUE TITLE
Unable to install as GnuPG is not found

### ISSUE THREAD

**Issue by frdbonif** [tacruc/gpgmailer#9]
Currently I'm running Nextcloud 19.0 on Ubuntu 18.04.

When I try to install the app it fails due to GnuPG not being installed.  I have verified that GnuPG is installed and the command `gpg` can be run by the www-data user.

Does anyone have a fix for this, or is the error mine?

**Comment by tacruc** [comment]
You have to install the php extension gnupg.
The package is usually called php_gnupg

Am Dienstag, 27. Oktober 2020, 09:49:56 CET schrieb frdbonif:
> Currently I'm running Nextcloud 19.0 on Ubuntu 18.04.
> 
> When I try to install the app it fails due to GnuPG not being installed. 
> I have verified that GnuPG is installed and the command `gpg` can be run
> by the www-data user.
> 
> Does anyone have a fix for this, or is the error mine?

**Comment by dmedinag** [comment]
this worked for me. In ubuntu, the package is `php-gnupg` (notice the hyphen instead of underscore)

**Comment by dmedinag** [comment]
Probably needs some better error message. Not finding "gnupg" is confusing, since what it's really missing is the php extension.
